"""PPA Google OAuth token management — extracted from arnoldlib for standalone use."""

from archive_auth.accounts import ACCOUNTS, INTERNAL_DOMAINS, is_internal_recipient
from archive_auth.token_manager import (
    CALENDAR_READONLY_SCOPES,
    CALENDAR_SCOPES,
    CONTACTS_READONLY_SCOPES,
    CONTACTS_SCOPES,
    DIRECTORY_READONLY_SCOPES,
    DRIVE_READONLY_SCOPES,
    DRIVE_SCOPES,
    FULL_SCOPES,
    GMAIL_READONLY_SCOPES,
    GMAIL_SCOPES,
    MINIMAL_SCOPES,
    READ_ONLY_SCOPES,
    SHEETS_READONLY_SCOPES,
    SHEETS_SCOPES,
    STANDARD_SCOPES,
    TASKS_READONLY_SCOPES,
    TASKS_SCOPES,
    GoogleCliTokenManager,
    account_name_from_email,
    build_google_cli_token_manager,
    load_google_oauth_client_config,
    load_local_refresh_token,
    load_refresh_token,
    mint_access_token,
    mint_refresh_token_via_browser,
    resolve_scopes,
)

__all__ = [
    "ACCOUNTS",
    "CALENDAR_READONLY_SCOPES",
    "CALENDAR_SCOPES",
    "CONTACTS_READONLY_SCOPES",
    "CONTACTS_SCOPES",
    "DIRECTORY_READONLY_SCOPES",
    "DRIVE_READONLY_SCOPES",
    "DRIVE_SCOPES",
    "FULL_SCOPES",
    "GMAIL_READONLY_SCOPES",
    "GMAIL_SCOPES",
    "GoogleCliTokenManager",
    "INTERNAL_DOMAINS",
    "MINIMAL_SCOPES",
    "READ_ONLY_SCOPES",
    "SHEETS_READONLY_SCOPES",
    "SHEETS_SCOPES",
    "STANDARD_SCOPES",
    "TASKS_READONLY_SCOPES",
    "TASKS_SCOPES",
    "account_name_from_email",
    "build_google_cli_token_manager",
    "is_internal_recipient",
    "load_google_oauth_client_config",
    "load_local_refresh_token",
    "load_refresh_token",
    "mint_access_token",
    "mint_refresh_token_via_browser",
    "resolve_scopes",
]
